from .home import home
from .project import project
from .event import event
from .classroom import classroom
from .join_us import join_us
from .testing import testing
from .reference import reference
from .pythonx_lessons_pages.pythonx_homepage import pythonx_homepage
from .pythonx_lessons_pages.pythonx_lesson1 import pythonx_lesson1
from .pythonx_lessons_pages.pythonx_lesson2 import pythonx_lesson2  
from .pythonx_lessons_pages.pythonx_lesson3 import pythonx_lesson3 